### ISSUE TITLE
Why pick Function over primitive variant?

### ISSUE THREAD

**Issue by Speiger** [SuperCoder7979/greggen#1]
I want to bring up the first issue because DBP showed me xD
https://github.com/SuperCoder7979/greggen/blob/5eac483a45759a051c9b3132e6d75899c271303c/src/main/java/supercoder79/greggen/util/BiomePicker.java#L13

Why do you use "Function<Integer, Integer>" instead of "IntUnaryOperator"?
Because technically that would work to without having to box and then unbox. Unless you require Integer over int.
(Tiny performance improvement)

**Comment by jaskarth** [comment]
I don't think the type matters here, for all ostensible purposes. The code isn't nearly hot enough for it to cause serious performance degradations, I'm pretty sure. The Function<> is easier to read and is what came to my mind first so I used it.

**Comment by Speiger** [comment]
Yeah boxing/unboxing causing constant object allocations/deallocations isn't really a problem at all. and the performance isn't hit by it. (Totally not the mc devs standing on performance)
