### ISSUE TITLE
Server crashes immediately with GregGen (BOP) world type

### ISSUE THREAD

**Issue by makamys** [SuperCoder7979/greggen#2]
The (integrated) server crashes immediately when creating a world with the "GregGen (BOP)" world type. The first commit with the issue is 08f1bc0f65d00443c98716fb93c51829b42f57d5, so this is probably caused by the shadow biome system missing BoP support. 

This happens with only GregGen + BoP + GT6 in the instance.

Crash log: [crash-2022-08-25_16.13.57-server.txt](https://github.com/SuperCoder7979/greggen/files/9425529/crash-2022-08-25_16.13.57-server.txt)

**Comment by jaskarth** [comment]
Oof, good catch. Will fix sometime soon.
